import {
  Home,
  Utensils,
  Car,
  HeartPulse,
  PartyPopper,
  Repeat,
  GraduationCap,
  ShoppingBag,
  MoreHorizontal,
  Wallet,
  Briefcase,
  TrendingUp,
  RotateCcw,
  Gift,
  Plane,
  Dumbbell,
  Dog,
  Baby,
  BookOpen,
  Phone,
  PiggyBank,
  Landmark,
  Shirt,
  Wrench,
  CreditCard,
  type LucideIcon,
} from "lucide-react";

export const CATEGORY_ICON_MAP: Record<string, LucideIcon> = {
  home: Home,
  utensils: Utensils,
  car: Car,
  "heart-pulse": HeartPulse,
  "party-popper": PartyPopper,
  repeat: Repeat,
  "graduation-cap": GraduationCap,
  "shopping-bag": ShoppingBag,
  "more-horizontal": MoreHorizontal,
  wallet: Wallet,
  briefcase: Briefcase,
  "trending-up": TrendingUp,
  "rotate-ccw": RotateCcw,
  gift: Gift,
  plane: Plane,
  dumbbell: Dumbbell,
  dog: Dog,
  baby: Baby,
  "book-open": BookOpen,
  phone: Phone,
  "piggy-bank": PiggyBank,
  landmark: Landmark,
  shirt: Shirt,
  wrench: Wrench,
  "credit-card": CreditCard,
};

export function getCategoryIcon(icon: string | null | undefined): LucideIcon {
  if (!icon) return MoreHorizontal;
  return CATEGORY_ICON_MAP[icon] ?? MoreHorizontal;
}
